import os
import random
import subprocess
import logging
import argparse

REPOS_DIR = os.path.join(os.path.dirname(__file__), "repos")
MEMORY_DIR = os.path.join(os.path.dirname(__file__), "memory")
REPOS_PER_RUN = 2
DEFAULT_AGENT = "claude"

GIT_NAME = os.environ.get("DAEMONCTL_GIT_NAME", "Eshaan0110")
GIT_EMAIL = os.environ.get("DAEMONCTL_GIT_EMAIL", "eshaan.adyanthaya@gmail.com")

BANNED_TRAILER_KEYWORDS = ("claude", "anthropic")
BANNED_BODY_SUBSTRINGS = (
    "claude code", "generated with", "generated by", "anthropic",
    "co-authored-by", "\U0001f916",
)

AGENTS = {
    "claude": {
        "name": "Claude Code",
        "build_cmd": lambda prompt: [
            "claude", "--dangerously-skip-permissions", "-p", prompt
        ],
    },
    "gemini": {
        "name": "Gemini CLI",
        "build_cmd": lambda prompt: [
            "gemini", "-p", prompt
        ],
    },
    "codex": {
        "name": "OpenAI Codex CLI",
        "build_cmd": lambda prompt: [
            "codex", "--approval-mode", "full-auto", "-q", prompt
        ],
    },
    "aider": {
        "name": "Aider",
        "build_cmd": lambda prompt: (
            ["aider", "--yes-always"]
            + (["--model", os.environ["AIDER_MODEL"]] if os.environ.get("AIDER_MODEL") else [])
            + ["--message", prompt]
        ),
    },
    "ollama": {
        "name": "Ollama (via aider, local + free)",
        "build_cmd": lambda prompt: [
            "aider", "--yes-always",
            "--model", f"ollama/{os.environ.get('OLLAMA_MODEL', 'qwen2.5-coder:7b')}",
            "--message", prompt,
        ],
    },
}

PROMPT_FIRST = """You are a developer working on this project. First read the codebase — README, source files, tests, comments — and understand what it does and what's missing.

Your job: build something SUBSTANTIAL. Add a real feature, complete an unfinished module, write a proper test suite, or add a working demo. Every commit must add real working functionality.

Do NOT commit any of these:
- Typo fixes, whitespace changes, formatting-only edits
- Comment additions or docstring tweaks on their own
- Trivial renames or code shuffles
- Anything you would be embarrassed to open a PR for

If you genuinely cannot find something meaningful to build, DO NOT COMMIT ANYTHING. Print ===NO_WORK=== and stop, then still emit the memory block below.

For every commit you DO make:
- Real working code, not filler
- Message: short imperative summary line, blank line, 1-2 sentences on WHY. No generic filler like "improve X", "update Y", "clean up".
- Do NOT add Co-authored-by, Signed-off-by, or any trailer
- Do NOT mention Claude, Anthropic, AI, LLM, automation, agents, assistants, or daemonctl anywhere — in commit messages, code, or comments

Push all commits to origin when done.

Then print your summary between the markers:

===MEMORY_START===
# {project name}

## Project summary
{2-3 sentences: what this project is, what stack it uses}

## Architecture
{folder structure overview, key files and what they do}

## Current state
{what's built, what works}

## Changelog
- {today's date}: {what you did in this run, or "no work needed"}

## Next priorities
- {ordered list of what to build next — be specific, name files/functions/features}

## Gotchas
- {any patterns, quirks, or things to watch out for}
===MEMORY_END===
===COMMITS_START===
{one commit SHA per line, or the word "none"}
===COMMITS_END==="""

PROMPT_MEMORY = """You are a developer working on this project. Here's your memory from previous runs:

{memory}

Pick the single most important item from "Next priorities" and build it. If that item is already done or no longer meaningful, look at the current state of the code and pick the next most meaningful thing to build.

If you genuinely cannot find anything meaningful to build, DO NOT COMMIT ANYTHING. Print ===NO_WORK=== and still emit the memory block below (append today's date + "no work needed" to the changelog).

For every commit you DO make:
- Real working code, not filler (no typo fixes, comment tweaks, whitespace, or trivial renames)
- Message: short imperative summary line, blank line, 1-2 sentences on WHY. No filler like "improve X" or "update Y".
- Do NOT add Co-authored-by, Signed-off-by, or any trailer
- Do NOT mention Claude, Anthropic, AI, LLM, automation, agents, assistants, or daemonctl anywhere — in commit messages, code, or comments

Push all commits to origin when done.

Then print the updated memory block (keep prior sections, update state, append today's changelog entry, refresh Next priorities):

===MEMORY_START===
{full memory block in the same format as before}
===MEMORY_END===
===COMMITS_START===
{one commit SHA per line, or the word "none"}
===COMMITS_END==="""

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger()


def get_repos():
    repos = []
    for name in os.listdir(REPOS_DIR):
        path = os.path.join(REPOS_DIR, name)
        if os.path.isdir(path) and os.path.isdir(os.path.join(path, ".git")):
            repos.append((name, path))
    return repos


def load_memory(repo_name):
    path = os.path.join(MEMORY_DIR, f"{repo_name}.md")
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    return None


def save_memory(repo_name, output):
    s = output.find("===MEMORY_START===")
    e = output.find("===MEMORY_END===")
    if s != -1 and e != -1:
        os.makedirs(MEMORY_DIR, exist_ok=True)
        with open(os.path.join(MEMORY_DIR, f"{repo_name}.md"), "w", encoding="utf-8") as f:
            f.write(output[s + 18:e].strip())
        log.info(f"  Memory saved")


def _git(path, args, env=None, check=True):
    r = subprocess.run(["git"] + args, cwd=path, env=env, text=True,
                       capture_output=True, check=False)
    if check and r.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)}: {r.stderr.strip()}")
    return r.stdout


def _git_head(path):
    try:
        return _git(path, ["rev-parse", "HEAD"]).strip()
    except Exception:
        return None


def _clean_message(msg):
    out = []
    for line in msg.splitlines():
        low = line.strip().lower()
        if low.startswith("co-authored-by:"):
            continue
        if low.startswith("signed-off-by:") and any(k in low for k in BANNED_TRAILER_KEYWORDS):
            continue
        if any(sub in low for sub in BANNED_BODY_SUBSTRINGS):
            continue
        out.append(line)
    text = "\n".join(out).strip()
    while "\n\n\n" in text:
        text = text.replace("\n\n\n", "\n\n")
    return text


def _scrub_and_push(path, base_sha, env):
    """Rewrite any new commits (base_sha..HEAD) to strip Claude mentions, then push."""
    if not base_sha:
        return
    shas = [s for s in _git(path, ["log", "--reverse", "--format=%H", f"{base_sha}..HEAD"]).splitlines() if s]
    if not shas:
        return

    rebuild = False
    payloads = []
    for sha in shas:
        msg = _git(path, ["log", "-1", "--format=%B", sha])
        tree = _git(path, ["log", "-1", "--format=%T", sha]).strip()
        cleaned = _clean_message(msg)
        payloads.append((tree, cleaned))
        if cleaned.strip() != msg.strip():
            rebuild = True

    if rebuild:
        parent = base_sha
        for tree, msg in payloads:
            r = subprocess.run(
                ["git", "commit-tree", tree, "-p", parent, "-m", msg],
                cwd=path, env=env, text=True, capture_output=True, check=True,
            )
            parent = r.stdout.strip()
        _git(path, ["reset", "--hard", parent])
        log.info("  Rewrote commits to strip AI mentions")

    push = subprocess.run(
        ["git", "push", "--force-with-lease"], cwd=path, env=env,
        capture_output=True, text=True, timeout=60,
    )
    if push.returncode != 0:
        log.warning(f"  push failed: {push.stderr.strip()}")


def _log_new_commits(path, base_sha):
    if not base_sha:
        return
    try:
        out = _git(path, ["log", "--stat", "--format=%h %an <%ae>%n  %s", f"{base_sha}..HEAD"])
    except Exception:
        return
    log.info("  Commits landed:")
    for line in out.splitlines():
        log.info(f"    {line}")


def run_agent(name, path, agent_key):
    agent = AGENTS[agent_key]
    memory = load_memory(name)
    prompt = PROMPT_MEMORY.replace("{memory}", memory) if memory else PROMPT_FIRST
    mode = "incremental" if memory else "first run"

    print(f"\n{'='*50}")
    print(f"  {name} ({agent['name']}, {mode})")
    print(f"{'='*50}\n")

    env = os.environ.copy()
    env.update({
        "GIT_AUTHOR_NAME": GIT_NAME,
        "GIT_AUTHOR_EMAIL": GIT_EMAIL,
        "GIT_COMMITTER_NAME": GIT_NAME,
        "GIT_COMMITTER_EMAIL": GIT_EMAIL,
    })

    head_before = _git_head(path)

    try:
        result = subprocess.run(
            agent["build_cmd"](prompt),
            cwd=path, text=True, env=env,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            timeout=1200,
            encoding="utf-8", errors="replace",
        )
    except subprocess.TimeoutExpired as e:
        print(f"\n✗ {name} — timeout after 20 min")
        if e.stdout:
            print("--- last output ---")
            print(e.stdout[-2000:] if isinstance(e.stdout, str) else e.stdout.decode("utf-8", "replace")[-2000:])
        return
    except Exception as e:
        print(f"\n✗ {name} — subprocess error: {e}")
        return

    if result.returncode != 0:
        print(f"\n✗ {name} (exit {result.returncode})")
        if result.stdout:
            print("--- output ---")
            print(result.stdout[-2000:])
        return

    head_after = _git_head(path)

    if head_before == head_after:
        print(f"\n○ {name} — no commits this run")
        save_memory(name, result.stdout)
        return

    try:
        _scrub_and_push(path, head_before, env)
    except Exception as e:
        log.warning(f"  scrub/push failed: {e}")
    _log_new_commits(path, head_before)

    print(f"\n✓ {name}")
    save_memory(name, result.stdout)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--agent", "-a", choices=list(AGENTS.keys()), default=DEFAULT_AGENT)
    parser.add_argument("--repos", "-n", type=int, default=REPOS_PER_RUN)
    parser.add_argument("--list-agents", action="store_true")
    args = parser.parse_args()

    if args.list_agents:
        for k, v in AGENTS.items():
            print(f"  {k:10s} — {v['name']}")
        return

    repos = get_repos()
    chosen = random.sample(repos, min(args.repos, len(repos)))
    print(f"Today's repos: {', '.join(n for n, _ in chosen)}\n")

    for name, path in chosen:
        try:
            run_agent(name, path, args.agent)
        except Exception as e:
            print(f"\n✗ {name} — crashed: {e}")
            log.exception("run_agent crash")


if __name__ == "__main__":
    main()